branch-defaults:
  master:
    environment: saasapp-dev
    group_suffix: null
global:
  application_name: saasapp
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.5 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
